objects=test.o memlib.o mm.o

test:$(objects)
	cc -o test $(objects)
test.o:test.c mm.h
	cc -c test.c
memlib.o:memlib.c memlib.h config.h
	cc -c memlib.c
mm.o:mm.c mm.h csapp.h
	cc -c mm.c

clean:
	rm $(objects)
